// import './js/zanyatie-s-mentorom-1.js';
// import './js/testModul-3-dz.js';
// import './js/testModul-3.js';
// import './js/testModul-4-dz.js';
// import './js/testModul-5-dz.js';
// import './js/testModul-6-dz.js';
// import './js/callback.js';
// import './js/calculator.js';
// import './js/dom.js';
